In [1]:
import pyodbc

In [67]:
# taking conncetion information
connection_string = (
    "DRIVER={ODBC Driver 17 for SQL Server};"
    "SERVER=DESKTOP-P5UVUF4;"
    "DATABASE=AdventureWorks2022;"
    "UID=اليوزر بتاعك;"
    "PWD=الباسورد بتاعك;"
)

def finding_null(table_name, primary_key):
    try:
    
    # Establish the connection
        connection = pyodbc.connect(connection_string)

        # Create a cursor from the connection
        cursor = connection.cursor()
    except Exception as e:
        return f"An error occurred: {e}"
    
    # extract columns of the table
    columns = cursor.execute(f"select column_name from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = '{table_name}';")
    
    # the output will be a list containing sum of tuples each tuble contains a column name we need to put all the column names
    # into one list
    table_columns = []
    for i in columns:
        for j in i:
            table_columns.append(j)
    # now we have a list containing all the column names
    
    for column in table_columns:
        # counting the null included in each column
        nulls_number = cursor.execute(
                f"select count({primary_key}) from Production.{table_name} where {column} is null")
        nulls_number = nulls_number.fetchall()
        
        # printing each column and its null counts
        print(f"column {column} has {nulls_number[0][0]} null values ")
        print("\n")
        print("="*50)

In [56]:
def finding_primary(table_name):
    
    columns = cursor.execute(f"select column_name from INFORMATION_SCHEMA.COLUMNS where TABLE_NAME = '{table_name}';")

        # the output will be a list containing sum of tuples each tuble contains a column name we need to put all the column names
        # into one list
    table_columns = []
    for i in columns:
        for j in i:
            table_columns.append(j)
    return table_columns[0]

In [57]:
finding_primary(all_tables[0])

'ProductID'

In [68]:
tables = cursor.execute("select table_name from INFORMATION_SCHEMA.TABLES where TABLE_SCHEMA = 'Production';")
all_tables = []
for i in tables:
    for j in i:
        all_tables.append(j)

In [70]:

for table in all_tables:
    print("*#"*25)
    print(f"Table: {table}")
    finding_null(table, finding_primary(table))

*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: Product
column ProductID has 0 null values


==================================================
column Name has 0 null values


==================================================
column ProductNumber has 0 null values


==================================================
column MakeFlag has 0 null values


==================================================
column FinishedGoodsFlag has 0 null values


==================================================
column Color has 248 null values


==================================================
column SafetyStockLevel has 0 null values


==================================================
column ReorderPoint has 0 null values


==================================================
column StandardCost has 0 null values


==================================================
column ListPrice has 0 null values


==================================================
column Size has 293 null values


==================================================
column SizeUnitMeasureCode has 328 null values


==================================================
column WeightUnitMeasureCode has 299 null values


==================================================
column Weight has 299 null values


==================================================
column DaysToManufacture has 0 null values


==================================================
column ProductLine has 226 null values


==================================================
column Class has 257 null values


==================================================
column Style has 293 null values


==================================================
column ProductSubcategoryID has 209 null values


==================================================
column ProductModelID has 209 null values


==================================================
column SellStartDate has 0 null values


==================================================
column SellEndDate has 406 null values


==================================================
column DiscontinuedDate has 504 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: vProductAndDescription
column ProductID has 0 null values


==================================================
column Name has 0 null values


==================================================
column ProductModel has 0 null values


==================================================
column CultureID has 0 null values


==================================================
column Description has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: vProductModelCatalogDescription
column ProductModelID has 0 null values


==================================================
column Name has 0 null values


==================================================
column Summary has 0 null values


==================================================
column Manufacturer has 0 null values


==================================================
column Copyright has 0 null values


==================================================
column ProductURL has 0 null values


==================================================
column WarrantyPeriod has 0 null values


==================================================
column WarrantyDescription has 0 null values


==================================================
column NoOfYears has 0 null values


==================================================
column MaintenanceDescription has 0 null values


==================================================
column Wheel has 1 null values


==================================================
column Saddle has 0 null values


==================================================
column Pedal has 0 null values


==================================================
column BikeFrame has 0 null values


==================================================
column Crankset has 3 null values


==================================================
column PictureAngle has 0 null values


==================================================
column PictureSize has 0 null values


==================================================
column ProductPhotoID has 0 null values


==================================================
column Material has 0 null values


==================================================
column Color has 0 null values


==================================================
column ProductLine has 0 null values


==================================================
column Style has 0 null values


==================================================
column RiderExperience has 0 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: vProductModelInstructions
column ProductModelID has 0 null values


==================================================
column Name has 0 null values


==================================================
column Instructions has 0 null values


==================================================
column LocationID has 0 null values


==================================================
column SetupHours has 81 null values


==================================================
column MachineHours has 86 null values


==================================================
column LaborHours has 0 null values


==================================================
column LotSize has 0 null values


==================================================
column Step has 0 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ScrapReason
column ScrapReasonID has 0 null values


==================================================
column Name has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductCategory
column ProductCategoryID has 0 null values


==================================================
column Name has 0 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductCostHistory
column ProductID has 0 null values


==================================================
column StartDate has 0 null values


==================================================
column EndDate has 195 null values


==================================================
column StandardCost has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductDescription
column ProductDescriptionID has 0 null values


==================================================
column Description has 0 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductDocument
column ProductID has 0 null values


==================================================
column DocumentNode has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductInventory
column ProductID has 0 null values


==================================================
column LocationID has 0 null values


==================================================
column Shelf has 0 null values


==================================================
column Bin has 0 null values


==================================================
column Quantity has 0 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductListPriceHistory
column ProductID has 0 null values


==================================================
column StartDate has 0 null values


==================================================
column EndDate has 195 null values


==================================================
column ListPrice has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductModel
column ProductModelID has 0 null values


==================================================
column Name has 0 null values


==================================================
column CatalogDescription has 122 null values


==================================================
column Instructions has 119 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductModelIllustration
column ProductModelID has 0 null values


==================================================
column IllustrationID has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductModelProductDescriptionCulture
column ProductModelID has 0 null values


==================================================
column ProductDescriptionID has 0 null values


==================================================
column CultureID has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: BillOfMaterials
column BillOfMaterialsID has 0 null values


==================================================
column ProductAssemblyID has 103 null values


==================================================
column ComponentID has 0 null values


==================================================
column StartDate has 0 null values


==================================================
column EndDate has 2480 null values


==================================================
column UnitMeasureCode has 0 null values


==================================================
column BOMLevel has 0 null values


==================================================
column PerAssemblyQty has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductPhoto
column ProductPhotoID has 0 null values


==================================================
column ThumbNailPhoto has 0 null values


==================================================
column ThumbnailPhotoFileName has 0 null values


==================================================
column LargePhoto has 0 null values


==================================================
column LargePhotoFileName has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductProductPhoto
column ProductID has 0 null values


==================================================
column ProductPhotoID has 0 null values


==================================================
column Primary has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: TransactionHistory
column TransactionID has 0 null values


==================================================
column ProductID has 0 null values


==================================================
column ReferenceOrderID has 0 null values


==================================================
column ReferenceOrderLineID has 0 null values


==================================================
column TransactionDate has 0 null values


==================================================
column TransactionType has 0 null values


==================================================
column Quantity has 0 null values


==================================================
column ActualCost has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductReview
column ProductReviewID has 0 null values


==================================================
column ProductID has 0 null values


==================================================
column ReviewerName has 0 null values


==================================================
column ReviewDate has 0 null values


==================================================
column EmailAddress has 0 null values


==================================================
column Rating has 0 null values


==================================================
column Comments has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: TransactionHistoryArchive
column TransactionID has 0 null values


==================================================
column ProductID has 0 null values


==================================================
column ReferenceOrderID has 0 null values


==================================================
column ReferenceOrderLineID has 0 null values


==================================================
column TransactionDate has 0 null values


==================================================
column TransactionType has 0 null values


==================================================
column Quantity has 0 null values


==================================================
column ActualCost has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: ProductSubcategory
column ProductSubcategoryID has 0 null values


==================================================
column ProductCategoryID has 0 null values


==================================================
column Name has 0 null values


==================================================
column rowguid has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: UnitMeasure
column UnitMeasureCode has 0 null values


==================================================
column Name has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: WorkOrder
column WorkOrderID has 0 null values


==================================================
column ProductID has 0 null values


==================================================
column OrderQty has 0 null values


==================================================
column StockedQty has 0 null values


==================================================
column ScrappedQty has 0 null values


==================================================
column StartDate has 0 null values


==================================================
column EndDate has 0 null values


==================================================
column DueDate has 0 null values


==================================================
column ScrapReasonID has 71862 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: Culture
column CultureID has 0 null values


==================================================
column Name has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: WorkOrderRouting
column WorkOrderID has 0 null values


==================================================
column ProductID has 0 null values


==================================================
column OperationSequence has 0 null values


==================================================
column LocationID has 0 null values


==================================================
column ScheduledStartDate has 0 null values


==================================================
column ScheduledEndDate has 0 null values


==================================================
column ActualStartDate has 0 null values


==================================================
column ActualEndDate has 0 null values


==================================================
column ActualResourceHrs has 0 null values


==================================================
column PlannedCost has 0 null values


==================================================
column ActualCost has 0 null values


==================================================
column ModifiedDate has 0 null values


==================================================
*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#*#
Table: Document
column DocumentNode has 0 null values


==================================================
column DocumentLevel has 0 null values


==================================================
column Title has 0 null values


==================================================
column Owner has 0 null values


==================================================
column FolderFlag has 0 null values


==================================================
column FileName has 0 null values


==================================================
column FileExtension has 0 null values


==================================================
column Revision has 0 null values


==================================================
column ChangeNumber has 0 null values


==================================================
column Status has 0 null values


==================================================
column DocumentSummary has 8 null values


==================================================
column Document has 4 null values



In [60]:
all_tables

['Product',
 'vProductAndDescription',
 'vProductModelCatalogDescription',
 'vProductModelInstructions',
 'ScrapReason',
 'ProductCategory',
 'ProductCostHistory',
 'ProductDescription',
 'ProductDocument',
 'ProductInventory',
 'ProductListPriceHistory',
 'ProductModel',
 'ProductModelIllustration',
 'ProductModelProductDescriptionCulture',
 'BillOfMaterials',
 'ProductPhoto',
 'ProductProductPhoto',
 'TransactionHistory',
 'ProductReview',
 'TransactionHistoryArchive',
 'ProductSubcategory',
 'UnitMeasure',
 'WorkOrder',
 'Culture',
 'WorkOrderRouting',
 'Document',
 'Illustration',
 'Location']